# Generated by Django 4.2.11 on 2024-03-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='measured_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('ph', 'Ph'), ('temperature', 'Temperature'), ('tds', 'Tds')], max_length=11),
        ),
    ]
